discord:
    bot:
        token: ${BOT_TOKEN}
    webhook:
        ztnet:
            id: ${DISCORD_WEBHOOK_ZTNET_ID}
            token: ${DISCORD_WEBHOOK_ZTNET_TOKEN}

spring:
    application:
        name: DECLARATIVE-bot
    profiles:
        active: dev  # DO NOT CHANGE HERE! Specify using `export SPRING_PROFILES_ACTIVE=prod`
